# Generated by Django 3.1.5 on 2021-04-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='to_user',
        ),
    ]
